# Generated by Django 4.2.23 on 2025-07-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('current_stock', models.IntegerField()),
                ('min_stock', models.IntegerField()),
                ('safety_stock', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('lead_time', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
