# Generated by Django 5.2.3 on 2025-07-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(help_text='매장 ID (고유 식별자)', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='매장 이름', max_length=100)),
                ('industry', models.CharField(help_text='산업 분야 (예: 편의점, 마트)', max_length=50)),
                ('region', models.CharField(help_text='매장 위치 지역', max_length=200)),
                ('open_time', models.TimeField(help_text='개점 시간')),
                ('close_time', models.TimeField(help_text='폐점 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='마지막 업데이트 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
            ],
            options={
                'verbose_name': '매장',
                'verbose_name_plural': '매장들',
            },
        ),
    ]
