# Generated by Django 4.2.23 on 2025-08-03 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='date',
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
