# Generated by Django 4.2.23 on 2025-08-03 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventorytransaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
