# Generated by Django 4.2.23 on 2025-07-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='price',
        ),
        migrations.AddField(
            model_name='sales',
            name='cost_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='is_event_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.store'),
        ),
    ]
